const Icons = [
    { name: 'icon-3d-rotation', group: 'Base Set' },
    { name: 'icon-accessibility', group: 'Base Set' },
    { name: 'icon-accessible', group: 'Base Set' },
    { name: 'icon-account-balance', group: 'Base Set' },
    { name: 'icon-account-balance-wallet', group: 'Base Set' },
    { name: 'icon-account-box', group: 'Base Set' },
    { name: 'icon-account-circle', group: 'Base Set' },
    { name: 'icon-add', group: 'Base Set' },
    { name: 'icon-alert', group: 'Base Set' },
    { name: 'icon-add-box', group: 'Base Set' },
    { name: 'icon-add-circle', group: 'Base Set' },
    { name: 'icon-add-circle-outline', group: 'Base Set' },
    { name: 'icon-add-shopping-cart', group: 'Base Set' },
    { name: 'icon-alarm', group: 'Base Set' },
    { name: 'icon-alarm-add', group: 'Base Set' },
    { name: 'icon-alarm-off', group: 'Base Set' },
    { name: 'icon-alarm-on', group: 'Base Set' },
    { name: 'icon-all-out', group: 'Base Set' },
    { name: 'icon-android', group: 'Base Set' },
    { name: 'icon-announcement', group: 'Base Set' },
    { name: 'icon-apps', group: 'Base Set' },
    { name: 'icon-archive', group: 'Base Set' },
    { name: 'icon-arrow-back', group: 'Base Set' },
    { name: 'icon-arrow-downward', group: 'Base Set' },
    { name: 'icon-arrow-drop-down', group: 'Base Set' },
    { name: 'icon-arrow-drop-down-circle', group: 'Base Set' },
    { name: 'icon-arrow-drop-up', group: 'Base Set' },
    { name: 'icon-arrow-forward', group: 'Base Set' },
    { name: 'icon-arrow-upward', group: 'Base Set' },
    { name: 'icon-aspect-ratio', group: 'Base Set' },
    { name: 'icon-assessment', group: 'Base Set' },
    { name: 'icon-assignment', group: 'Base Set' },
    { name: 'icon-assignment-ind', group: 'Base Set' },
    { name: 'icon-assignment-late', group: 'Base Set' },
    { name: 'icon-assignment-return', group: 'Base Set' },
    { name: 'icon-assignment-returned', group: 'Base Set' },
    { name: 'icon-assignment-turned-in', group: 'Base Set' },
    { name: 'icon-attachment', group: 'Base Set' },
    { name: 'icon-autorenew', group: 'Base Set' },
    { name: 'icon-backspace', group: 'Base Set' },
    { name: 'icon-backup', group: 'Base Set' },
    { name: 'icon-block', group: 'Base Set' },
    { name: 'icon-book', group: 'Base Set' },
    { name: 'icon-bookmark', group: 'Base Set' },
    { name: 'icon-bookmark-border', group: 'Base Set' },
    { name: 'icon-bug-report', group: 'Base Set' },
    { name: 'icon-build', group: 'Base Set' },
    { name: 'icon-cached', group: 'Base Set' },
    { name: 'icon-camera-enhance', group: 'Base Set' },
    { name: 'icon-cancel', group: 'Base Set' },
    { name: 'icon-card-giftcard', group: 'Base Set' },
    { name: 'icon-card-membership', group: 'Base Set' },
    { name: 'icon-card-travel', group: 'Base Set' },
    { name: 'icon-change-history', group: 'Base Set' },
    { name: 'icon-check', group: 'Base Set' },
    { name: 'icon-check-box', group: 'Base Set' },
    { name: 'icon-check-box-outline-blank', group: 'Base Set' },
    { name: 'icon-check-circle', group: 'Base Set' },
    { name: 'icon-chevron-left', group: 'Base Set' },
    { name: 'icon-chevron-right', group: 'Base Set' },
    { name: 'icon-chrome-reader-mode', group: 'Base Set' },
    { name: 'icon-class', group: 'Base Set' },
    { name: 'icon-clear', group: 'Base Set' },
    { name: 'icon-close', group: 'Base Set' },
    { name: 'icon-cloud', group: 'Base Set' },
    { name: 'icon-cloud-circle', group: 'Base Set' },
    { name: 'icon-cloud-done', group: 'Base Set' },
    { name: 'icon-cloud-download', group: 'Base Set' },
    { name: 'icon-cloud-off', group: 'Base Set' },
    { name: 'icon-cloud-queue', group: 'Base Set' },
    { name: 'icon-cloud-upload', group: 'Base Set' },
    { name: 'icon-code', group: 'Base Set' },
    { name: 'icon-compare-arrows', group: 'Base Set' },
    { name: 'icon-content-copy', group: 'Base Set' },
    { name: 'icon-content-cut', group: 'Base Set' },
    { name: 'icon-content-paste', group: 'Base Set' },
    { name: 'icon-copyright', group: 'Base Set' },
    { name: 'icon-create', group: 'Base Set' },
    { name: 'icon-create-new-folder', group: 'Base Set' },
    { name: 'icon-credit-card', group: 'Base Set' },
    { name: 'icon-dashboard', group: 'Base Set' },
    { name: 'icon-date-range', group: 'Base Set' },
    { name: 'icon-delete', group: 'Base Set' },
    { name: 'icon-delete-forever', group: 'Base Set' },
    { name: 'icon-delete-sweep', group: 'Base Set' },
    { name: 'icon-description', group: 'Base Set' },
    { name: 'icon-dns', group: 'Base Set' },
    { name: 'icon-done', group: 'Base Set' },
    { name: 'icon-done-all', group: 'Base Set' },
    { name: 'icon-donut-large', group: 'Base Set' },
    { name: 'icon-donut-small', group: 'Base Set' },
    { name: 'icon-drafts', group: 'Base Set' },
    { name: 'icon-eject', group: 'Base Set' },
    { name: 'icon-error', group: 'Base Set' },
    { name: 'icon-error-outline', group: 'Base Set' },
    { name: 'icon-euro-symbol', group: 'Base Set' },
    { name: 'icon-event', group: 'Base Set' },
    { name: 'icon-event-seat', group: 'Base Set' },
    { name: 'icon-exit-to-app', group: 'Base Set' },
    { name: 'icon-expand-less', group: 'Base Set' },
    { name: 'icon-expand-more', group: 'Base Set' },
    { name: 'icon-explore', group: 'Base Set' },
    { name: 'icon-extension', group: 'Base Set' },
    { name: 'icon-face', group: 'Base Set' },
    { name: 'icon-favorite', group: 'Base Set' },
    { name: 'icon-favorite-border', group: 'Base Set' },
    { name: 'icon-feedback', group: 'Base Set' },
    { name: 'icon-file-download', group: 'Base Set' },
    { name: 'icon-file-upload', group: 'Base Set' },
    { name: 'icon-filter-list', group: 'Base Set' },
    { name: 'icon-find-in-page', group: 'Base Set' },
    { name: 'icon-find-replace', group: 'Base Set' },
    { name: 'icon-fingerprint', group: 'Base Set' },
    { name: 'icon-first-page', group: 'Base Set' },
    { name: 'icon-flag', group: 'Base Set' },
    { name: 'icon-flight-land', group: 'Base Set' },
    { name: 'icon-flight-takeoff', group: 'Base Set' },
    { name: 'icon-flip-to-back', group: 'Base Set' },
    { name: 'icon-flip-to-front', group: 'Base Set' },
    { name: 'icon-folder', group: 'Base Set' },
    { name: 'icon-folder-open', group: 'Base Set' },
    { name: 'icon-folder-shared', group: 'Base Set' },
    { name: 'icon-font-download', group: 'Base Set' },
    { name: 'icon-forward', group: 'Base Set' },
    { name: 'icon-fullscreen', group: 'Base Set' },
    { name: 'icon-fullscreen-exit', group: 'Base Set' },
    { name: 'icon-g-translate', group: 'Base Set' },
    { name: 'icon-gavel', group: 'Base Set' },
    { name: 'icon-gesture', group: 'Base Set' },
    { name: 'icon-get-app', group: 'Base Set' },
    { name: 'icon-gif', group: 'Base Set' },
    { name: 'icon-grade', group: 'Base Set' },
    { name: 'icon-group-work', group: 'Base Set' },
    { name: 'icon-help', group: 'Base Set' },
    { name: 'icon-help-outline', group: 'Base Set' },
    { name: 'icon-highlight-off', group: 'Base Set' },
    { name: 'icon-history', group: 'Base Set' },
    { name: 'icon-home', group: 'Base Set' },
    { name: 'icon-hourglass-empty', group: 'Base Set' },
    { name: 'icon-hourglass-full', group: 'Base Set' },
    { name: 'icon-http', group: 'Base Set' },
    { name: 'icon-https', group: 'Base Set' },
    { name: 'icon-important-devices', group: 'Base Set' },
    { name: 'icon-inbox', group: 'Base Set' },
    { name: 'icon-indeterminate-check-box', group: 'Base Set' },
    { name: 'icon-info', group: 'Base Set' },
    { name: 'icon-info-outline', group: 'Base Set' },
    { name: 'icon-input', group: 'Base Set' },
    { name: 'icon-invert-colors', group: 'Base Set' },
    { name: 'icon-label', group: 'Base Set' },
    { name: 'icon-label-outline', group: 'Base Set' },
    { name: 'icon-language', group: 'Base Set' },
    { name: 'icon-last-page', group: 'Base Set' },
    { name: 'icon-launch', group: 'Base Set' },
    { name: 'icon-lightbulb-outline', group: 'Base Set' },
    { name: 'icon-line-style', group: 'Base Set' },
    { name: 'icon-line-weight', group: 'Base Set' },
    { name: 'icon-link', group: 'Base Set' },
    { name: 'icon-list', group: 'Base Set' },
    { name: 'icon-lock', group: 'Base Set' },
    { name: 'icon-lock-open', group: 'Base Set' },
    { name: 'icon-lock-outline', group: 'Base Set' },
    { name: 'icon-low-priority', group: 'Base Set' },
    { name: 'icon-loyalty', group: 'Base Set' },
    { name: 'icon-mail', group: 'Base Set' },
    { name: 'icon-markunread', group: 'Base Set' },
    { name: 'icon-markunread-mailbox', group: 'Base Set' },
    { name: 'icon-menu', group: 'Base Set' },
    { name: 'icon-more-horiz', group: 'Base Set' },
    { name: 'icon-more-vert', group: 'Base Set' },
    { name: 'icon-motorcycle', group: 'Base Set' },
    { name: 'icon-move-to-inbox', group: 'Base Set' },
    { name: 'icon-next-week', group: 'Base Set' },
    { name: 'icon-note-add', group: 'Base Set' },
    { name: 'icon-offline-pin', group: 'Base Set' },
    { name: 'icon-opacity', group: 'Base Set' },
    { name: 'icon-open-in-browser', group: 'Base Set' },
    { name: 'icon-open-in-new', group: 'Base Set' },
    { name: 'icon-open-with', group: 'Base Set' },
    { name: 'icon-pageview', group: 'Base Set' },
    { name: 'icon-pan-tool', group: 'Base Set' },
    { name: 'icon-payment', group: 'Base Set' },
    { name: 'icon-perm-camera-mic', group: 'Base Set' },
    { name: 'icon-perm-contact-calendar', group: 'Base Set' },
    { name: 'icon-perm-data-setting', group: 'Base Set' },
    { name: 'icon-perm-device-information', group: 'Base Set' },
    { name: 'icon-perm-identity', group: 'Base Set' },
    { name: 'icon-perm-media', group: 'Base Set' },
    { name: 'icon-perm-phone-msg', group: 'Base Set' },
    { name: 'icon-perm-scan-wifi', group: 'Base Set' },
    { name: 'icon-pets', group: 'Base Set' },
    { name: 'icon-picture-in-picture', group: 'Base Set' },
    { name: 'icon-picture-in-picture-alt', group: 'Base Set' },
    { name: 'icon-play-for-work', group: 'Base Set' },
    { name: 'icon-polymer', group: 'Base Set' },
    { name: 'icon-power-settings-new', group: 'Base Set' },
    { name: 'icon-pregnant-woman', group: 'Base Set' },
    { name: 'icon-print', group: 'Base Set' },
    { name: 'icon-query-builder', group: 'Base Set' },
    { name: 'icon-question-answer', group: 'Base Set' },
    { name: 'icon-radio-button-checked', group: 'Base Set' },
    { name: 'icon-radio-button-unchecked', group: 'Base Set' },
    { name: 'icon-receipt', group: 'Base Set' },
    { name: 'icon-record-voice-over', group: 'Base Set' },
    { name: 'icon-redeem', group: 'Base Set' },
    { name: 'icon-redo', group: 'Base Set' },
    { name: 'icon-refresh', group: 'Base Set' },
    { name: 'icon-remove', group: 'Base Set' },
    { name: 'icon-remove-circle', group: 'Base Set' },
    { name: 'icon-remove-circle-outline', group: 'Base Set' },
    { name: 'icon-remove-shopping-cart', group: 'Base Set' },
    { name: 'icon-reorder', group: 'Base Set' },
    { name: 'icon-reply', group: 'Base Set' },
    { name: 'icon-reply-all', group: 'Base Set' },
    { name: 'icon-report', group: 'Base Set' },
    { name: 'icon-report-problem', group: 'Base Set' },
    { name: 'icon-restore', group: 'Base Set' },
    { name: 'icon-restore-page', group: 'Base Set' },
    { name: 'icon-room', group: 'Base Set' },
    { name: 'icon-rounded-corner', group: 'Base Set' },
    { name: 'icon-rowing', group: 'Base Set' },
    { name: 'icon-save', group: 'Base Set' },
    { name: 'icon-schedule', group: 'Base Set' },
    { name: 'icon-search', group: 'Base Set' },
    { name: 'icon-select-all', group: 'Base Set' },
    { name: 'icon-send', group: 'Base Set' },
    { name: 'icon-settings', group: 'Base Set' },
    { name: 'icon-settings-applications', group: 'Base Set' },
    { name: 'icon-settings-backup-restore', group: 'Base Set' },
    { name: 'icon-settings-bluetooth', group: 'Base Set' },
    { name: 'icon-settings-brightness', group: 'Base Set' },
    { name: 'icon-settings-cell', group: 'Base Set' },
    { name: 'icon-settings-ethernet', group: 'Base Set' },
    { name: 'icon-settings-input-antenna', group: 'Base Set' },
    { name: 'icon-settings-input-component', group: 'Base Set' },
    { name: 'icon-settings-input-composite', group: 'Base Set' },
    { name: 'icon-settings-input-hdmi', group: 'Base Set' },
    { name: 'icon-settings-input-svideo', group: 'Base Set' },
    { name: 'icon-settings-overscan', group: 'Base Set' },
    { name: 'icon-settings-phone', group: 'Base Set' },
    { name: 'icon-settings-power', group: 'Base Set' },
    { name: 'icon-settings-remote', group: 'Base Set' },
    { name: 'icon-settings-voice', group: 'Base Set' },
    { name: 'icon-shop', group: 'Base Set' },
    { name: 'icon-shop-two', group: 'Base Set' },
    { name: 'icon-shopping-basket', group: 'Base Set' },
    { name: 'icon-shopping-cart', group: 'Base Set' },
    { name: 'icon-sort', group: 'Base Set' },
    { name: 'icon-speaker-notes', group: 'Base Set' },
    { name: 'icon-speaker-notes-off', group: 'Base Set' },
    { name: 'icon-spellcheck', group: 'Base Set' },
    { name: 'icon-star', group: 'Base Set' },
    { name: 'icon-star-border', group: 'Base Set' },
    { name: 'icon-star-half', group: 'Base Set' },
    { name: 'icon-stars', group: 'Base Set' },
    { name: 'icon-store', group: 'Base Set' },
    { name: 'icon-subdirectory-arrow-left', group: 'Base Set' },
    { name: 'icon-subdirectory-arrow-right', group: 'Base Set' },
    { name: 'icon-subject', group: 'Base Set' },
    { name: 'icon-supervisor-account', group: 'Base Set' },
    { name: 'icon-swap-horiz', group: 'Base Set' },
    { name: 'icon-swap-vert', group: 'Base Set' },
    { name: 'icon-swap-vertical-circle', group: 'Base Set' },
    { name: 'icon-system-update-alt', group: 'Base Set' },
    { name: 'icon-tab', group: 'Base Set' },
    { name: 'icon-tab-unselected', group: 'Base Set' },
    { name: 'icon-text-format', group: 'Base Set' },
    { name: 'icon-theaters', group: 'Base Set' },
    { name: 'icon-thumb-down', group: 'Base Set' },
    { name: 'icon-thumb-up', group: 'Base Set' },
    { name: 'icon-thumbs-up-down', group: 'Base Set' },
    { name: 'icon-timeline', group: 'Base Set' },
    { name: 'icon-toc', group: 'Base Set' },
    { name: 'icon-today', group: 'Base Set' },
    { name: 'icon-toll', group: 'Base Set' },
    { name: 'icon-touch-app', group: 'Base Set' },
    { name: 'icon-track-changes', group: 'Base Set' },
    { name: 'icon-translate', group: 'Base Set' },
    { name: 'icon-trending-down', group: 'Base Set' },
    { name: 'icon-trending-flat', group: 'Base Set' },
    { name: 'icon-trending-up', group: 'Base Set' },
    { name: 'icon-turned-in', group: 'Base Set' },
    { name: 'icon-turned-in-not', group: 'Base Set' },
    { name: 'icon-unarchive', group: 'Base Set' },
    { name: 'icon-undo', group: 'Base Set' },
    { name: 'icon-unfold-less', group: 'Base Set' },
    { name: 'icon-unfold-more', group: 'Base Set' },
    { name: 'icon-update', group: 'Base Set' },
    { name: 'icon-verified-user', group: 'Base Set' },
    { name: 'icon-view-agenda', group: 'Base Set' },
    { name: 'icon-view-array', group: 'Base Set' },
    { name: 'icon-view-carousel', group: 'Base Set' },
    { name: 'icon-view-column', group: 'Base Set' },
    { name: 'icon-view-day', group: 'Base Set' },
    { name: 'icon-view-headline', group: 'Base Set' },
    { name: 'icon-view-list', group: 'Base Set' },
    { name: 'icon-view-module', group: 'Base Set' },
    { name: 'icon-view-quilt', group: 'Base Set' },
    { name: 'icon-view-stream', group: 'Base Set' },
    { name: 'icon-view-week', group: 'Base Set' },
    { name: 'icon-visibility', group: 'Base Set' },
    { name: 'icon-visibility-off', group: 'Base Set' },
    { name: 'icon-warning', group: 'Base Set' },
    { name: 'icon-watch-later', group: 'Base Set' },
    { name: 'icon-weekend', group: 'Base Set' },
    { name: 'icon-work', group: 'Base Set' },
    { name: 'icon-youtube-searched-for', group: 'Base Set' },
    { name: 'icon-zoom-in', group: 'Base Set' },
    { name: 'icon-zoom-out', group: 'Base Set' },


    { name: 'icon-attach-file', group: 'Editor' },
    { name: 'icon-attach-money', group: 'Editor' },
    { name: 'icon-border-all', group: 'Editor' },
    { name: 'icon-border-bottom', group: 'Editor' },
    { name: 'icon-border-clear', group: 'Editor' },
    { name: 'icon-border-color', group: 'Editor' },
    { name: 'icon-border-horizontal', group: 'Editor' },
    { name: 'icon-border-inner', group: 'Editor' },
    { name: 'icon-border-left', group: 'Editor' },
    { name: 'icon-border-outer', group: 'Editor' },
    { name: 'icon-border-right', group: 'Editor' },
    { name: 'icon-border-style', group: 'Editor' },
    { name: 'icon-border-top', group: 'Editor' },
    { name: 'icon-border-vertical', group: 'Editor' },
    { name: 'icon-bubble-chart', group: 'Editor' },
    { name: 'icon-drag-handle', group: 'Editor' },
    { name: 'icon-format-align-center', group: 'Editor' },
    { name: 'icon-format-align-justify', group: 'Editor' },
    { name: 'icon-format-align-left', group: 'Editor' },
    { name: 'icon-format-align-right', group: 'Editor' },
    { name: 'icon-format-bold', group: 'Editor' },
    { name: 'icon-format-clear', group: 'Editor' },
    { name: 'icon-format-color-fill', group: 'Editor' },
    { name: 'icon-format-color-reset', group: 'Editor' },
    { name: 'icon-format-color-text', group: 'Editor' },
    { name: 'icon-format-indent-decrease', group: 'Editor' },
    { name: 'icon-format-indent-increase', group: 'Editor' },
    { name: 'icon-format-italic', group: 'Editor' },
    { name: 'icon-format-line-spacing', group: 'Editor' },
    { name: 'icon-format-list-bulleted', group: 'Editor' },
    { name: 'icon-format-list-numbered', group: 'Editor' },
    { name: 'icon-format-paint', group: 'Editor' },
    { name: 'icon-format-quote', group: 'Editor' },
    { name: 'icon-format-shapes', group: 'Editor' },
    { name: 'icon-format-size', group: 'Editor' },
    { name: 'icon-format-strikethrough', group: 'Editor' },
    { name: 'icon-format-textdirection-l-to-r', group: 'Editor' },
    { name: 'icon-format-textdirection-r-to-l', group: 'Editor' },
    { name: 'icon-format-underlined', group: 'Editor' },
    { name: 'icon-functions', group: 'Editor' },
    { name: 'icon-highlight', group: 'Editor' },
    { name: 'icon-insert-chart', group: 'Editor' },
    { name: 'icon-insert-comment', group: 'Editor' },
    { name: 'icon-insert-drive-file', group: 'Editor' },
    { name: 'icon-insert-emoticon', group: 'Editor' },
    { name: 'icon-insert-invitation', group: 'Editor' },
    { name: 'icon-insert-link', group: 'Editor' },
    { name: 'icon-insert-photo', group: 'Editor' },
    { name: 'icon-linear-scale', group: 'Editor' },
    { name: 'icon-merge-type', group: 'Editor' },
    { name: 'icon-mode-comment', group: 'Editor' },
    { name: 'icon-mode-edit', group: 'Editor' },
    { name: 'icon-monetization-on', group: 'Editor' },
    { name: 'icon-money-off', group: 'Editor' },
    { name: 'icon-multiline-chart', group: 'Editor' },
    { name: 'icon-pie-chart', group: 'Editor' },
    { name: 'icon-pie-chart-outlined', group: 'Editor' },
    { name: 'icon-publish', group: 'Editor' },
    { name: 'icon-short-text', group: 'Editor' },
    { name: 'icon-show-chart', group: 'Editor' },
    { name: 'icon-space-bar', group: 'Editor' },
    { name: 'icon-strikethrough-s', group: 'Editor' },
    { name: 'icon-text-fields', group: 'Editor' },
    { name: 'icon-title', group: 'Editor' },
    { name: 'icon-vertical-align-bottom', group: 'Editor' },
    { name: 'icon-vertical-align-center', group: 'Editor' },
    { name: 'icon-vertical-align-top', group: 'Editor' },
    { name: 'icon-wrap-text', group: 'Editor' },


    { name: 'icon-cast', group: 'Hardware' },
    { name: 'icon-cast-connected', group: 'Hardware' },
    { name: 'icon-computer', group: 'Hardware' },
    { name: 'icon-desktop-mac', group: 'Hardware' },
    { name: 'icon-desktop-windows', group: 'Hardware' },
    { name: 'icon-developer-board', group: 'Hardware' },
    { name: 'icon-device-hub', group: 'Hardware' },
    { name: 'icon-devices-other', group: 'Hardware' },
    { name: 'icon-dock', group: 'Hardware' },
    { name: 'icon-gamepad', group: 'Hardware' },
    { name: 'icon-headset', group: 'Hardware' },
    { name: 'icon-headset-mic', group: 'Hardware' },
    { name: 'icon-keyboard', group: 'Hardware' },
    { name: 'icon-keyboard-arrow-down', group: 'Hardware' },
    { name: 'icon-keyboard-arrow-left', group: 'Hardware' },
    { name: 'icon-keyboard-arrow-right', group: 'Hardware' },
    { name: 'icon-keyboard-arrow-up', group: 'Hardware' },
    { name: 'icon-keyboard-backspace', group: 'Hardware' },
    { name: 'icon-keyboard-capslock', group: 'Hardware' },
    { name: 'icon-keyboard-hide', group: 'Hardware' },
    { name: 'icon-keyboard-return', group: 'Hardware' },
    { name: 'icon-keyboard-tab', group: 'Hardware' },
    { name: 'icon-keyboard-voice', group: 'Hardware' },
    { name: 'icon-laptop', group: 'Hardware' },
    { name: 'icon-laptop-chromebook', group: 'Hardware' },
    { name: 'icon-laptop-mac', group: 'Hardware' },
    { name: 'icon-laptop-windows', group: 'Hardware' },
    { name: 'icon-memory', group: 'Hardware' },
    { name: 'icon-mouse', group: 'Hardware' },
    { name: 'icon-phone-android', group: 'Hardware' },
    { name: 'icon-phone-iphone', group: 'Hardware' },
    { name: 'icon-phonelink', group: 'Hardware' },
    { name: 'icon-phonelink-off', group: 'Hardware' },
    { name: 'icon-power-input', group: 'Hardware' },
    { name: 'icon-router', group: 'Hardware' },
    { name: 'icon-scanner', group: 'Hardware' },
    { name: 'icon-security', group: 'Hardware' },
    { name: 'icon-sim-card', group: 'Hardware' },
    { name: 'icon-smartphone', group: 'Hardware' },
    { name: 'icon-speaker', group: 'Hardware' },
    { name: 'icon-speaker-group', group: 'Hardware' },
    { name: 'icon-tablet', group: 'Hardware' },
    { name: 'icon-tablet-android', group: 'Hardware' },
    { name: 'icon-tablet-mac', group: 'Hardware' },
    { name: 'icon-toys', group: 'Hardware' },
    { name: 'icon-tv', group: 'Hardware' },
    { name: 'icon-videogame-asset', group: 'Hardware' },
    { name: 'icon-watch', group: 'Hardware' },


    { name: 'icon-add-a-photo', group: 'Image' },
    { name: 'icon-add-to-photos', group: 'Image' },
    { name: 'icon-adjust', group: 'Image' },
    { name: 'icon-assistant', group: 'Image' },
    { name: 'icon-assistant-photo', group: 'Image' },
    { name: 'icon-audiotrack', group: 'Image' },
    { name: 'icon-blur-circular', group: 'Image' },
    { name: 'icon-blur-linear', group: 'Image' },
    { name: 'icon-blur-off', group: 'Image' },
    { name: 'icon-blur-on', group: 'Image' },
    { name: 'icon-brightness-1', group: 'Image' },
    { name: 'icon-brightness-2', group: 'Image' },
    { name: 'icon-brightness-3', group: 'Image' },
    { name: 'icon-brightness-4', group: 'Image' },
    { name: 'icon-brightness-5', group: 'Image' },
    { name: 'icon-brightness-6', group: 'Image' },
    { name: 'icon-brightness-7', group: 'Image' },
    { name: 'icon-broken-image', group: 'Image' },
    { name: 'icon-brush', group: 'Image' },
    { name: 'icon-burst-mode', group: 'Image' },
    { name: 'icon-camera', group: 'Image' },
    { name: 'icon-camera-alt', group: 'Image' },
    { name: 'icon-camera-front', group: 'Image' },
    { name: 'icon-camera-rear', group: 'Image' },
    { name: 'icon-camera-roll', group: 'Image' },
    { name: 'icon-center-focus-strong', group: 'Image' },
    { name: 'icon-center-focus-weak', group: 'Image' },
    { name: 'icon-collections', group: 'Image' },
    { name: 'icon-collections-bookmark', group: 'Image' },
    { name: 'icon-color-lens', group: 'Image' },
    { name: 'icon-colorize', group: 'Image' },
    { name: 'icon-compare', group: 'Image' },
    { name: 'icon-control-point', group: 'Image' },
    { name: 'icon-control-point-duplicate', group: 'Image' },
    { name: 'icon-crop', group: 'Image' },
    { name: 'icon-crop-16-9', group: 'Image' },
    { name: 'icon-crop-3-2', group: 'Image' },
    { name: 'icon-crop-5-4', group: 'Image' },
    { name: 'icon-crop-7-5', group: 'Image' },
    { name: 'icon-crop-din', group: 'Image' },
    { name: 'icon-crop-free', group: 'Image' },
    { name: 'icon-crop-landscape', group: 'Image' },
    { name: 'icon-crop-original', group: 'Image' },
    { name: 'icon-crop-portrait', group: 'Image' },
    { name: 'icon-crop-rotate', group: 'Image' },
    { name: 'icon-crop-square', group: 'Image' },
    { name: 'icon-dehaze', group: 'Image' },
    { name: 'icon-details', group: 'Image' },
    { name: 'icon-edit', group: 'Image' },
    { name: 'icon-exposure', group: 'Image' },
    { name: 'icon-exposure-neg-1', group: 'Image' },
    { name: 'icon-exposure-neg-2', group: 'Image' },
    { name: 'icon-exposure-plus-1', group: 'Image' },
    { name: 'icon-exposure-plus-2', group: 'Image' },
    { name: 'icon-exposure-zero', group: 'Image' },
    { name: 'icon-filter', group: 'Image' },
    { name: 'icon-filter-1', group: 'Image' },
    { name: 'icon-filter-2', group: 'Image' },
    { name: 'icon-filter-3', group: 'Image' },
    { name: 'icon-filter-4', group: 'Image' },
    { name: 'icon-filter-5', group: 'Image' },
    { name: 'icon-filter-6', group: 'Image' },
    { name: 'icon-filter-7', group: 'Image' },
    { name: 'icon-filter-8', group: 'Image' },
    { name: 'icon-filter-9', group: 'Image' },
    { name: 'icon-filter-9-plus', group: 'Image' },
    { name: 'icon-filter-b-and-w', group: 'Image' },
    { name: 'icon-filter-center-focus', group: 'Image' },
    { name: 'icon-filter-drama', group: 'Image' },
    { name: 'icon-filter-frames', group: 'Image' },
    { name: 'icon-filter-hdr', group: 'Image' },
    { name: 'icon-filter-none', group: 'Image' },
    { name: 'icon-filter-tilt-shift', group: 'Image' },
    { name: 'icon-filter-vintage', group: 'Image' },
    { name: 'icon-flare', group: 'Image' },
    { name: 'icon-flash-auto', group: 'Image' },
    { name: 'icon-flash-off', group: 'Image' },
    { name: 'icon-flash-on', group: 'Image' },
    { name: 'icon-flip', group: 'Image' },
    { name: 'icon-gradient', group: 'Image' },
    { name: 'icon-grain', group: 'Image' },
    { name: 'icon-grid-off', group: 'Image' },
    { name: 'icon-grid-on', group: 'Image' },
    { name: 'icon-hdr-off', group: 'Image' },
    { name: 'icon-hdr-on', group: 'Image' },
    { name: 'icon-hdr-strong', group: 'Image' },
    { name: 'icon-hdr-weak', group: 'Image' },
    { name: 'icon-healing', group: 'Image' },
    { name: 'icon-image', group: 'Image' },
    { name: 'icon-image-aspect-ratio', group: 'Image' },
    { name: 'icon-iso', group: 'Image' },
    { name: 'icon-landscape', group: 'Image' },
    { name: 'icon-leak-add', group: 'Image' },
    { name: 'icon-leak-remove', group: 'Image' },
    { name: 'icon-lens', group: 'Image' },
    { name: 'icon-linked-camera', group: 'Image' },
    { name: 'icon-looks', group: 'Image' },
    { name: 'icon-looks-3', group: 'Image' },
    { name: 'icon-looks-4', group: 'Image' },
    { name: 'icon-looks-5', group: 'Image' },
    { name: 'icon-looks-6', group: 'Image' },
    { name: 'icon-looks-one', group: 'Image' },
    { name: 'icon-looks-two', group: 'Image' },
    { name: 'icon-loupe', group: 'Image' },
    { name: 'icon-monochrome-photos', group: 'Image' },
    { name: 'icon-movie-creation', group: 'Image' },
    { name: 'icon-movie-filter', group: 'Image' },
    { name: 'icon-music-note', group: 'Image' },
    { name: 'icon-nature', group: 'Image' },
    { name: 'icon-nature-people', group: 'Image' },
    { name: 'icon-navigate-before', group: 'Image' },
    { name: 'icon-navigate-next', group: 'Image' },
    { name: 'icon-palette', group: 'Image' },
    { name: 'icon-panorama', group: 'Image' },
    { name: 'icon-panorama-fish-eye', group: 'Image' },
    { name: 'icon-panorama-horizontal', group: 'Image' },
    { name: 'icon-panorama-vertical', group: 'Image' },
    { name: 'icon-panorama-wide-angle', group: 'Image' },
    { name: 'icon-photo', group: 'Image' },
    { name: 'icon-photo-album', group: 'Image' },
    { name: 'icon-photo-camera', group: 'Image' },
    { name: 'icon-photo-filter', group: 'Image' },
    { name: 'icon-photo-library', group: 'Image' },
    { name: 'icon-photo-size-select-actual', group: 'Image' },
    { name: 'icon-photo-size-select-large', group: 'Image' },
    { name: 'icon-photo-size-select-small', group: 'Image' },
    { name: 'icon-picture-as-pdf', group: 'Image' },
    { name: 'icon-portrait', group: 'Image' },
    { name: 'icon-remove-red-eye', group: 'Image' },
    { name: 'icon-rotate-90-degrees-ccw', group: 'Image' },
    { name: 'icon-rotate-left', group: 'Image' },
    { name: 'icon-rotate-right', group: 'Image' },
    { name: 'icon-slideshow', group: 'Image' },
    { name: 'icon-straighten', group: 'Image' },
    { name: 'icon-style', group: 'Image' },
    { name: 'icon-switch-camera', group: 'Image' },
    { name: 'icon-switch-video', group: 'Image' },
    { name: 'icon-tag-faces', group: 'Image' },
    { name: 'icon-texture', group: 'Image' },
    { name: 'icon-timelapse', group: 'Image' },
    { name: 'icon-timer', group: 'Image' },
    { name: 'icon-timer-10', group: 'Image' },
    { name: 'icon-timer-3', group: 'Image' },
    { name: 'icon-timer-off', group: 'Image' },
    { name: 'icon-tonality', group: 'Image' },
    { name: 'icon-transform', group: 'Image' },
    { name: 'icon-tune', group: 'Image' },
    { name: 'icon-view-comfy', group: 'Image' },
    { name: 'icon-view-compact', group: 'Image' },
    { name: 'icon-vignette', group: 'Image' },
    { name: 'icon-wb-auto', group: 'Image' },
    { name: 'icon-wb-cloudy', group: 'Image' },
    { name: 'icon-wb-incandescent', group: 'Image' },
    { name: 'icon-wb-iridescent', group: 'Image' },
    { name: 'icon-wb-sunny', group: 'Image' },


    { name: 'icon-add-location', group: 'Map' },
    { name: 'icon-beenhere', group: 'Map' },
    { name: 'icon-directions', group: 'Map' },
    { name: 'icon-directions-bike', group: 'Map' },
    { name: 'icon-directions-boat', group: 'Map' },
    { name: 'icon-directions-bus', group: 'Map' },
    { name: 'icon-directions-car', group: 'Map' },
    { name: 'icon-directions-railway', group: 'Map' },
    { name: 'icon-directions-run', group: 'Map' },
    { name: 'icon-directions-subway', group: 'Map' },
    { name: 'icon-directions-transit', group: 'Map' },
    { name: 'icon-directions-walk', group: 'Map' },
    { name: 'icon-edit-location', group: 'Map' },
    { name: 'icon-ev-station', group: 'Map' },
    { name: 'icon-flight', group: 'Map' },
    { name: 'icon-hotel', group: 'Map' },
    { name: 'icon-layers', group: 'Map' },
    { name: 'icon-layers-clear', group: 'Map' },
    { name: 'icon-local-activity', group: 'Map' },
    { name: 'icon-local-airport', group: 'Map' },
    { name: 'icon-local-atm', group: 'Map' },
    { name: 'icon-local-bar', group: 'Map' },
    { name: 'icon-local-cafe', group: 'Map' },
    { name: 'icon-local-car-wash', group: 'Map' },
    { name: 'icon-local-convenience-store', group: 'Map' },
    { name: 'icon-local-dining', group: 'Map' },
    { name: 'icon-local-drink', group: 'Map' },
    { name: 'icon-local-florist', group: 'Map' },
    { name: 'icon-local-gas-station', group: 'Map' },
    { name: 'icon-local-grocery-store', group: 'Map' },
    { name: 'icon-local-hospital', group: 'Map' },
    { name: 'icon-local-hotel', group: 'Map' },
    { name: 'icon-local-laundry-service', group: 'Map' },
    { name: 'icon-local-library', group: 'Map' },
    { name: 'icon-local-mall', group: 'Map' },
    { name: 'icon-local-movies', group: 'Map' },
    { name: 'icon-local-offer', group: 'Map' },
    { name: 'icon-local-parking', group: 'Map' },
    { name: 'icon-local-pharmacy', group: 'Map' },
    { name: 'icon-local-phone', group: 'Map' },
    { name: 'icon-local-pizza', group: 'Map' },
    { name: 'icon-local-play', group: 'Map' },
    { name: 'icon-local-post-office', group: 'Map' },
    { name: 'icon-local-printshop', group: 'Map' },
    { name: 'icon-local-see', group: 'Map' },
    { name: 'icon-local-shipping', group: 'Map' },
    { name: 'icon-local-taxi', group: 'Map' },
    { name: 'icon-map', group: 'Map' },
    { name: 'icon-my-location', group: 'Map' },
    { name: 'icon-navigation', group: 'Map' },
    { name: 'icon-near-me', group: 'Map' },
    { name: 'icon-person-pin', group: 'Map' },
    { name: 'icon-person-pin-circle', group: 'Map' },
    { name: 'icon-pin-drop', group: 'Map' },
    { name: 'icon-place', group: 'Map' },
    { name: 'icon-rate-review', group: 'Map' },
    { name: 'icon-restaurant', group: 'Map' },
    { name: 'icon-restaurant-menu', group: 'Map' },
    { name: 'icon-satellite', group: 'Map' },
    { name: 'icon-store-mall-directory', group: 'Map' },
    { name: 'icon-streetview', group: 'Map' },
    { name: 'icon-subway', group: 'Map' },
    { name: 'icon-terrain', group: 'Map' },
    { name: 'icon-traffic', group: 'Map' },
    { name: 'icon-train', group: 'Map' },
    { name: 'icon-tram', group: 'Map' },
    { name: 'icon-transfer-within-a-station', group: 'Map' },
    { name: 'icon-zoom-out-map', group: 'Map' },


    { name: 'icon-adb', group: 'Notification' },
    { name: 'icon-airline-seat-flat', group: 'Notification' },
    { name: 'icon-airline-seat-flat-angled', group: 'Notification' },
    { name: 'icon-airline-seat-individual-suite', group: 'Notification' },
    { name: 'icon-airline-seat-legroom-extra', group: 'Notification' },
    { name: 'icon-airline-seat-legroom-normal', group: 'Notification' },
    { name: 'icon-airline-seat-legroom-reduced', group: 'Notification' },
    { name: 'icon-airline-seat-recline-extra', group: 'Notification' },
    { name: 'icon-airline-seat-recline-normal', group: 'Notification' },
    { name: 'icon-bluetooth-audio', group: 'Notification' },
    { name: 'icon-confirmation-number', group: 'Notification' },
    { name: 'icon-disc-full', group: 'Notification' },
    { name: 'icon-do-not-disturb', group: 'Notification' },
    { name: 'icon-do-not-disturb-alt', group: 'Notification' },
    { name: 'icon-do-not-disturb-off', group: 'Notification' },
    { name: 'icon-do-not-disturb-on', group: 'Notification' },
    { name: 'icon-drive-eta', group: 'Notification' },
    { name: 'icon-enhanced-encryption', group: 'Notification' },
    { name: 'icon-event-available', group: 'Notification' },
    { name: 'icon-event-busy', group: 'Notification' },
    { name: 'icon-event-note', group: 'Notification' },
    { name: 'icon-folder-special', group: 'Notification' },
    { name: 'icon-live-tv', group: 'Notification' },
    { name: 'icon-mms', group: 'Notification' },
    { name: 'icon-more', group: 'Notification' },
    { name: 'icon-network-check', group: 'Notification' },
    { name: 'icon-network-locked', group: 'Notification' },
    { name: 'icon-no-encryption', group: 'Notification' },
    { name: 'icon-ondemand-video', group: 'Notification' },
    { name: 'icon-personal-video', group: 'Notification' },
    { name: 'icon-phone-bluetooth-speaker', group: 'Notification' },
    { name: 'icon-phone-forwarded', group: 'Notification' },
    { name: 'icon-phone-in-talk', group: 'Notification' },
    { name: 'icon-phone-locked', group: 'Notification' },
    { name: 'icon-phone-missed', group: 'Notification' },
    { name: 'icon-phone-paused', group: 'Notification' },
    { name: 'icon-power', group: 'Notification' },
    { name: 'icon-priority-high', group: 'Notification' },
    { name: 'icon-rv-hookup', group: 'Notification' },
    { name: 'icon-sd-card', group: 'Notification' },
    { name: 'icon-sim-card-alert', group: 'Notification' },
    { name: 'icon-sms', group: 'Notification' },
    { name: 'icon-sms-failed', group: 'Notification' },
    { name: 'icon-sync', group: 'Notification' },
    { name: 'icon-sync-disabled', group: 'Notification' },
    { name: 'icon-sync-problem', group: 'Notification' },
    { name: 'icon-system-update', group: 'Notification' },
    { name: 'icon-tap-and-play', group: 'Notification' },
    { name: 'icon-time-to-leave', group: 'Notification' },
    { name: 'icon-vibration', group: 'Notification' },
    { name: 'icon-voice-chat', group: 'Notification' },
    { name: 'icon-vpn-lock', group: 'Notification' },
    { name: 'icon-wc', group: 'Notification' },
    { name: 'icon-wifi', group: 'Notification' },


    { name: 'icon-ac-unit', group: 'Places' },
    { name: 'icon-airport-shuttle', group: 'Places' },
    { name: 'icon-all-inclusive', group: 'Places' },
    { name: 'icon-beach-access', group: 'Places' },
    { name: 'icon-business-center', group: 'Places' },
    { name: 'icon-casino', group: 'Places' },
    { name: 'icon-child-care', group: 'Places' },
    { name: 'icon-child-friendly', group: 'Places' },
    { name: 'icon-fitness-center', group: 'Places' },
    { name: 'icon-free-breakfast', group: 'Places' },
    { name: 'icon-golf-course', group: 'Places' },
    { name: 'icon-hot-tub', group: 'Places' },
    { name: 'icon-kitchen', group: 'Places' },
    { name: 'icon-pool', group: 'Places' },
    { name: 'icon-room-service', group: 'Places' },
    { name: 'icon-rv-hookup', group: 'Places' },
    { name: 'icon-smoke-free', group: 'Places' },
    { name: 'icon-smoking-rooms', group: 'Places' },
    { name: 'icon-spa', group: 'Places' },


    { name: 'icon-cake', group: 'Social' },
    { name: 'icon-domain', group: 'Social' },
    { name: 'icon-group', group: 'Social' },
    { name: 'icon-group-add', group: 'Social' },
    { name: 'icon-location-city', group: 'Social' },
    { name: 'icon-mood', group: 'Social' },
    { name: 'icon-mood-bad', group: 'Social' },
    { name: 'icon-notifications', group: 'Social' },
    { name: 'icon-notifications-active', group: 'Social' },
    { name: 'icon-notifications-none', group: 'Social' },
    { name: 'icon-notifications-off', group: 'Social' },
    { name: 'icon-notifications-paused', group: 'Social' },
    { name: 'icon-pages', group: 'Social' },
    { name: 'icon-party-mode', group: 'Social' },
    { name: 'icon-people', group: 'Social' },
    { name: 'icon-people-outline', group: 'Social' },
    { name: 'icon-person', group: 'Social' },
    { name: 'icon-person-add', group: 'Social' },
    { name: 'icon-person-outline', group: 'Social' },
    { name: 'icon-plus-one', group: 'Social' },
    { name: 'icon-poll', group: 'Social' },
    { name: 'icon-public', group: 'Social' },
    { name: 'icon-school', group: 'Social' },
    { name: 'icon-sentiment-dissatisfied', group: 'Social' },
    { name: 'icon-sentiment-neutral', group: 'Social' },
    { name: 'icon-sentiment-satisfied', group: 'Social' },
    { name: 'icon-sentiment-very-dissatisfied', group: 'Social' },
    { name: 'icon-sentiment-very-satisfied', group: 'Social' },
    { name: 'icon-share', group: 'Social' },
    { name: 'icon-whatshot', group: 'Social' },

]

export default Icons;